--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-08-27 15:33:55

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 228 (class 1259 OID 74240)
-- Name: guru; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.guru (
    id_guru bigint NOT NULL,
    nama_guru character varying(255),
    nip character varying(100),
    id_user integer NOT NULL
);


ALTER TABLE public.guru OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 74239)
-- Name: guru_id_guru_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.guru_id_guru_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.guru_id_guru_seq OWNER TO postgres;

--
-- TOC entry 4968 (class 0 OID 0)
-- Dependencies: 227
-- Name: guru_id_guru_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.guru_id_guru_seq OWNED BY public.guru.id_guru;


--
-- TOC entry 218 (class 1259 OID 16970)
-- Name: jenis_kegiatan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jenis_kegiatan (
    id_jenis_kegiatan bigint NOT NULL,
    nama_kegiatan character varying(255) NOT NULL
);


ALTER TABLE public.jenis_kegiatan OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16969)
-- Name: jenis_kegiatan_id_jenis_kegiatan_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.jenis_kegiatan_id_jenis_kegiatan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.jenis_kegiatan_id_jenis_kegiatan_seq OWNER TO postgres;

--
-- TOC entry 4969 (class 0 OID 0)
-- Dependencies: 217
-- Name: jenis_kegiatan_id_jenis_kegiatan_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.jenis_kegiatan_id_jenis_kegiatan_seq OWNED BY public.jenis_kegiatan.id_jenis_kegiatan;


--
-- TOC entry 226 (class 1259 OID 41386)
-- Name: kegiatan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kegiatan (
    id_kegiatan bigint NOT NULL,
    id_guru bigint,
    id_jenis_kegiatan bigint,
    id_kelas bigint,
    tanggal date,
    jam_mulai time without time zone,
    jam_selesai time without time zone,
    laporan text,
    created_at timestamp without time zone,
    id_status bigint
);


ALTER TABLE public.kegiatan OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 41385)
-- Name: kegiatan_id_kegiatan_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kegiatan ALTER COLUMN id_kegiatan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kegiatan_id_kegiatan_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 33204)
-- Name: kelas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kelas (
    id_kelas integer NOT NULL,
    tingkat character varying(10) NOT NULL,
    jurusan character varying(50) NOT NULL
);


ALTER TABLE public.kelas OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 33203)
-- Name: kelas_id_kelas_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.kelas_id_kelas_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.kelas_id_kelas_seq OWNER TO postgres;

--
-- TOC entry 4970 (class 0 OID 0)
-- Dependencies: 219
-- Name: kelas_id_kelas_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.kelas_id_kelas_seq OWNED BY public.kelas.id_kelas;


--
-- TOC entry 230 (class 1259 OID 74252)
-- Name: murid; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.murid (
    id_murid bigint NOT NULL,
    nama_murid character varying(255),
    nis character varying(100),
    id_user integer NOT NULL
);


ALTER TABLE public.murid OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 74251)
-- Name: murid_id_murid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.murid_id_murid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.murid_id_murid_seq OWNER TO postgres;

--
-- TOC entry 4971 (class 0 OID 0)
-- Dependencies: 229
-- Name: murid_id_murid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.murid_id_murid_seq OWNED BY public.murid.id_murid;


--
-- TOC entry 224 (class 1259 OID 41354)
-- Name: status_kegiatan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.status_kegiatan (
    id_status integer NOT NULL,
    status character varying(50) NOT NULL
);


ALTER TABLE public.status_kegiatan OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 41353)
-- Name: status_kegiatan_id_status_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.status_kegiatan_id_status_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.status_kegiatan_id_status_seq OWNER TO postgres;

--
-- TOC entry 4972 (class 0 OID 0)
-- Dependencies: 223
-- Name: status_kegiatan_id_status_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.status_kegiatan_id_status_seq OWNED BY public.status_kegiatan.id_status;


--
-- TOC entry 222 (class 1259 OID 33250)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id_user bigint NOT NULL,
    username character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    level character varying(255),
    status character varying(20) DEFAULT 'pending'::character varying
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 33249)
-- Name: users_id_user_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_user_seq OWNER TO postgres;

--
-- TOC entry 4973 (class 0 OID 0)
-- Dependencies: 221
-- Name: users_id_user_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_user_seq OWNED BY public.users.id_user;


--
-- TOC entry 4777 (class 2604 OID 74243)
-- Name: guru id_guru; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.guru ALTER COLUMN id_guru SET DEFAULT nextval('public.guru_id_guru_seq'::regclass);


--
-- TOC entry 4772 (class 2604 OID 16973)
-- Name: jenis_kegiatan id_jenis_kegiatan; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jenis_kegiatan ALTER COLUMN id_jenis_kegiatan SET DEFAULT nextval('public.jenis_kegiatan_id_jenis_kegiatan_seq'::regclass);


--
-- TOC entry 4773 (class 2604 OID 33207)
-- Name: kelas id_kelas; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kelas ALTER COLUMN id_kelas SET DEFAULT nextval('public.kelas_id_kelas_seq'::regclass);


--
-- TOC entry 4778 (class 2604 OID 74255)
-- Name: murid id_murid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.murid ALTER COLUMN id_murid SET DEFAULT nextval('public.murid_id_murid_seq'::regclass);


--
-- TOC entry 4776 (class 2604 OID 41357)
-- Name: status_kegiatan id_status; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.status_kegiatan ALTER COLUMN id_status SET DEFAULT nextval('public.status_kegiatan_id_status_seq'::regclass);


--
-- TOC entry 4774 (class 2604 OID 33253)
-- Name: users id_user; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN id_user SET DEFAULT nextval('public.users_id_user_seq'::regclass);


--
-- TOC entry 4960 (class 0 OID 74240)
-- Dependencies: 228
-- Data for Name: guru; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.guru (id_guru, nama_guru, nip, id_user) FROM stdin;
\.


--
-- TOC entry 4950 (class 0 OID 16970)
-- Dependencies: 218
-- Data for Name: jenis_kegiatan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jenis_kegiatan (id_jenis_kegiatan, nama_kegiatan) FROM stdin;
1	Pelajaran
\.


--
-- TOC entry 4958 (class 0 OID 41386)
-- Dependencies: 226
-- Data for Name: kegiatan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kegiatan (id_kegiatan, id_guru, id_jenis_kegiatan, id_kelas, tanggal, jam_mulai, jam_selesai, laporan, created_at, id_status) FROM stdin;
\.


--
-- TOC entry 4952 (class 0 OID 33204)
-- Dependencies: 220
-- Data for Name: kelas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kelas (id_kelas, tingkat, jurusan) FROM stdin;
1	X	RPL
2	X	BROADCAST
3	X	ANIMASI
4	XI	RPL
5	XI	BROADCAST
9	XI	ANIMASI
10	XII	RPL
11	XII	BROADCAST
12	XII	ANIMASI
\.


--
-- TOC entry 4962 (class 0 OID 74252)
-- Dependencies: 230
-- Data for Name: murid; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.murid (id_murid, nama_murid, nis, id_user) FROM stdin;
\.


--
-- TOC entry 4956 (class 0 OID 41354)
-- Dependencies: 224
-- Data for Name: status_kegiatan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.status_kegiatan (id_status, status) FROM stdin;
1	Direncanakan
2	Berlangsung
3	Selesai
4	Dibatalkan
\.


--
-- TOC entry 4954 (class 0 OID 33250)
-- Dependencies: 222
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id_user, username, email, password, level, status) FROM stdin;
5	Guru	guru@gmail.com	$2y$10$SQbIYCy21ADAKF3IOn5ejORRJQiFoBaAPWe4V2qLmTDCVZXXKrcqm	guru	pending
2	murid	murid@gmail.com	$2y$10$UGjvNnpxMaD9C2RH7v2YhuHwGPXa.Eq03gIOndYN2Cq.TicCOpxoS	murid	pending
1	admin	admin@gmail.com	$2y$10$eBUCGJYDUSSlE9w.Oj/KjOlbI3ejjWHQs5tpB2K76V6vJsN1CRLYu	admin	pending
\.


--
-- TOC entry 4974 (class 0 OID 0)
-- Dependencies: 227
-- Name: guru_id_guru_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.guru_id_guru_seq', 1, false);


--
-- TOC entry 4975 (class 0 OID 0)
-- Dependencies: 217
-- Name: jenis_kegiatan_id_jenis_kegiatan_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jenis_kegiatan_id_jenis_kegiatan_seq', 1, true);


--
-- TOC entry 4976 (class 0 OID 0)
-- Dependencies: 225
-- Name: kegiatan_id_kegiatan_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kegiatan_id_kegiatan_seq1', 9, true);


--
-- TOC entry 4977 (class 0 OID 0)
-- Dependencies: 219
-- Name: kelas_id_kelas_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kelas_id_kelas_seq', 1, false);


--
-- TOC entry 4978 (class 0 OID 0)
-- Dependencies: 229
-- Name: murid_id_murid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.murid_id_murid_seq', 1, false);


--
-- TOC entry 4979 (class 0 OID 0)
-- Dependencies: 223
-- Name: status_kegiatan_id_status_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.status_kegiatan_id_status_seq', 4, true);


--
-- TOC entry 4980 (class 0 OID 0)
-- Dependencies: 221
-- Name: users_id_user_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_user_seq', 1, false);


--
-- TOC entry 4795 (class 2606 OID 74245)
-- Name: guru guru_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.guru
    ADD CONSTRAINT guru_pkey PRIMARY KEY (id_guru);


--
-- TOC entry 4780 (class 2606 OID 16975)
-- Name: jenis_kegiatan jenis_kegiatan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jenis_kegiatan
    ADD CONSTRAINT jenis_kegiatan_pkey PRIMARY KEY (id_jenis_kegiatan);


--
-- TOC entry 4793 (class 2606 OID 41392)
-- Name: kegiatan kegiatan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kegiatan
    ADD CONSTRAINT kegiatan_pkey PRIMARY KEY (id_kegiatan);


--
-- TOC entry 4782 (class 2606 OID 33209)
-- Name: kelas kelas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kelas
    ADD CONSTRAINT kelas_pkey PRIMARY KEY (id_kelas);


--
-- TOC entry 4797 (class 2606 OID 74257)
-- Name: murid murid_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.murid
    ADD CONSTRAINT murid_pkey PRIMARY KEY (id_murid);


--
-- TOC entry 4789 (class 2606 OID 41359)
-- Name: status_kegiatan status_kegiatan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.status_kegiatan
    ADD CONSTRAINT status_kegiatan_pkey PRIMARY KEY (id_status);


--
-- TOC entry 4791 (class 2606 OID 41361)
-- Name: status_kegiatan status_kegiatan_status_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.status_kegiatan
    ADD CONSTRAINT status_kegiatan_status_key UNIQUE (status);


--
-- TOC entry 4785 (class 2606 OID 74169)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4787 (class 2606 OID 33257)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id_user);


--
-- TOC entry 4783 (class 1259 OID 74209)
-- Name: idx_users_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_users_status ON public.users USING btree (status);


--
-- TOC entry 4802 (class 2606 OID 74246)
-- Name: guru fk_id_user_guru; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.guru
    ADD CONSTRAINT fk_id_user_guru FOREIGN KEY (id_user) REFERENCES public.users(id_user) ON DELETE CASCADE;


--
-- TOC entry 4803 (class 2606 OID 74258)
-- Name: murid fk_id_user_murid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.murid
    ADD CONSTRAINT fk_id_user_murid FOREIGN KEY (id_user) REFERENCES public.users(id_user) ON DELETE CASCADE;


--
-- TOC entry 4798 (class 2606 OID 74263)
-- Name: kegiatan fk_kegiatan_guru; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kegiatan
    ADD CONSTRAINT fk_kegiatan_guru FOREIGN KEY (id_guru) REFERENCES public.guru(id_guru);


--
-- TOC entry 4799 (class 2606 OID 41398)
-- Name: kegiatan fk_kegiatan_jenis; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kegiatan
    ADD CONSTRAINT fk_kegiatan_jenis FOREIGN KEY (id_jenis_kegiatan) REFERENCES public.jenis_kegiatan(id_jenis_kegiatan);


--
-- TOC entry 4800 (class 2606 OID 41403)
-- Name: kegiatan fk_kegiatan_kelas; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kegiatan
    ADD CONSTRAINT fk_kegiatan_kelas FOREIGN KEY (id_kelas) REFERENCES public.kelas(id_kelas);


--
-- TOC entry 4801 (class 2606 OID 41408)
-- Name: kegiatan fk_kegiatan_status; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kegiatan
    ADD CONSTRAINT fk_kegiatan_status FOREIGN KEY (id_status) REFERENCES public.status_kegiatan(id_status);


-- Completed on 2025-08-27 15:33:55

--
-- PostgreSQL database dump complete
--

